[package]
name = "versions"
version = "3.0.2"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"
description = "A library for parsing and comparing software version numbers."
homepage = "https://github.com/fosskers/rs-versions"
repository = "https://github.com/fosskers/rs-versions"
readme = "README.md"
license = "MIT"
keywords = ["version", "compare", "semantic"]
categories = ["parser-implementations"]

[dependencies]
nom = "6.0"
itertools = "0.10"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
version-sync = "0.9"
